package com.desj.configuration;

/**
 * Created by Julien on 22.04.16.
 * <p>
 * Configuration for spring security. This allows user to access the front page "/login",
 * but no other site without a password.
 * Please DO NOT edit this file, unless you are 100% sure what you are doing!
 *
 */

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.security.SecurityProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.authentication.configurers.provisioning.JdbcUserDetailsManagerConfigurer;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.provisioning.JdbcUserDetailsManager;

@Configuration
@ComponentScan(basePackages = "com.desj")
@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    @Autowired
    private DataSource dataSource;

    /*
    *  TODO: Delete authorization on /console
    *  fullyAuthenticated won't let user to stay logged in
    * */
    @Override
    protected void configure(HttpSecurity httpSecurity) throws Exception {
        httpSecurity.authorizeRequests().antMatchers("/console/**", "/About", "/SignUp").permitAll().anyRequest().fullyAuthenticated()
                // This line of code sets the /login as a default page, if the user isn't authenticated
                .and().formLogin().loginPage("/login").permitAll()
                // logout needs permit too
                .and().logout().permitAll();

        httpSecurity.headers().frameOptions().disable();
    }

    @Bean
    public JdbcUserDetailsManager jdbcUserDetailsManager(DataSource dataSource) {
        JdbcUserDetailsManager detailsManager = new JdbcUserDetailsManager();
        detailsManager.setDataSource(dataSource);
        return detailsManager;
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder authenticationManagerBuilder,
                                JdbcUserDetailsManager detailsManager, DataSource dataSource,
                                BCryptPasswordEncoder encoder) throws Exception {
        authenticationManagerBuilder.userDetailsService(detailsManager);
        JdbcUserDetailsManagerConfigurer<AuthenticationManagerBuilder> configurer = new JdbcUserDetailsManagerConfigurer<>(detailsManager);
        authenticationManagerBuilder.apply(configurer);
        configurer.dataSource(dataSource).withDefaultSchema().passwordEncoder(encoder);
    }

    @Bean
    public BCryptPasswordEncoder encoder() {
        return new BCryptPasswordEncoder();
    }
}